version: "3.9"

x-environment: &default-environment
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  SECRET_KEY: change_me_to_something_random # best to run openssl rand -hex 32
  PORT: 8000 # If changing, change the web service port too
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: https://glitchtip.example.com # Change this to your domain
  DEFAULT_FROM_EMAIL: email@example.com # Change this to your email
  CELERY_WORKER_AUTOSCALE: "1,3" # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.

x-depends_on: &default-depends_on
  - postgres
  - redis

services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./back
    container_name: todo-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
      - SENTRY_DSN=http://f323e6a50dbc47ba8f38e8ad4ea4eb6c@web:8000/1
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  frontend:
    build: ./front
    container_name: todo-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_SENTRY_DSN=http://frontend_key@glitchtip:8001/1
    ports:
      - "5173:80"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust" # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - glitchtip_pgdata:/var/lib/postgresql/data

  redis:
    image: valkey/valkey
    restart: unless-stopped

  web:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - "8001:8000"
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

  migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    command: ./bin/run-migrate.sh
    environment: *default-environment



volumes:
  mongo_data:
  glitchtip_pgdata:
  uploads: