version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./back
    container_name: todo-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  frontend:
    build: ./front
    container_name: todo-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    ports:
      - "5173:80"

volumes:
  mongo_data:
